//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Charts')
export class ChartsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  chartName: string;

  @Column('date', { nullable: true })
  date: Date;

  @Column('integer', { nullable: true })
  ranking: number;

  @Column('integer', { nullable: true })
  song: number;

  @Column('integer', { nullable: true })
  platform: number;
}
