//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ChartsTitle = () => {
  const record = useRecordContext();
  return <span>Charts {record ? `"${record.chartName}"` : ''}</span>;
};

export const ChartsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="chartName" />
      <DateField source="date" />
      <NumberField source="ranking" />
      <ReferenceField source="song" reference="Songs" />
      <ReferenceField source="platform" reference="Platforms" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ChartsEdit = () => (
  <Edit title={<ChartsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="chartName" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="ranking" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="song" reference="Songs" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="platform" reference="Platforms" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ChartsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="chartName" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="ranking" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="song" reference="Songs" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="platform" reference="Platforms" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  <ReferenceInput source="song" label="song" reference="Songs" alwaysOn />,
  <ReferenceInput
    source="platform"
    label="platform"
    reference="Platforms"
    alwaysOn
  />,
];
