//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Analysis Update App on Music Chart" />
    <CardContent>
      Analyzing music charts across various platforms like YouTube, Spotify,
      Apple Music, iTunes, Amazon Music, Shazam, and Pandora provides a
      comprehensive view of an artist’s performance and the music consumption
      trends globally.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
