//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Artists: {
      name: 'Artists',
      fields: { name: 'Name', genre: 'Genre', country: 'Country', id: 'id' },
    },
    Songs: {
      name: 'Songs',
      fields: {
        title: 'Title',
        releaseDate: 'Release Date',
        artist: 'Artist',
        genre: 'Genre',
        id: 'id',
      },
    },
    Albums: {
      name: 'Albums',
      fields: {
        title: 'Title',
        releaseDate: 'Release Date',
        artist: 'Artist',
        songs: 'Songs',
        id: 'id',
      },
    },
    Charts: {
      name: 'Charts',
      fields: {
        chartName: 'Chart Name',
        date: 'Date',
        ranking: 'Ranking',
        song: 'Song',
        platform: 'Platform',
        id: 'id',
      },
    },
    Platforms: {
      name: 'Platforms',
      fields: { name: 'Name', type: 'Type', region: 'Region', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    Artists: {
      name: 'Artists (fr)',
      fields: {
        name: 'Name (fr)',
        genre: 'Genre (fr)',
        country: 'Country (fr)',
        id: 'id',
      },
    },
    Songs: {
      name: 'Songs (fr)',
      fields: {
        title: 'Title (fr)',
        releaseDate: 'Release Date (fr)',
        artist: 'Artist (fr)',
        genre: 'Genre (fr)',
        id: 'id',
      },
    },
    Albums: {
      name: 'Albums (fr)',
      fields: {
        title: 'Title (fr)',
        releaseDate: 'Release Date (fr)',
        artist: 'Artist (fr)',
        songs: 'Songs (fr)',
        id: 'id',
      },
    },
    Charts: {
      name: 'Charts (fr)',
      fields: {
        chartName: 'Chart Name (fr)',
        date: 'Date (fr)',
        ranking: 'Ranking (fr)',
        song: 'Song (fr)',
        platform: 'Platform (fr)',
        id: 'id',
      },
    },
    Platforms: {
      name: 'Platforms (fr)',
      fields: {
        name: 'Name (fr)',
        type: 'Type (fr)',
        region: 'Region (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
